Multi-language support (zh/en/ja) with nuxt-i18n
lianginx/chatgpt-nuxt pull request #13
Opened 2023-05-13 17:14 UTC by itTkm

@lianginx Thank you for your great project.

I have implemented multilingual support by introducing nuxt-i18n.
Please check it out.

2023-05-13 21:42 UTC, lianginx commented
Wow! Thank you very much for your code. I will merge it after the test!

Thank you again for your contribution. You have helped me achieve the small goal of "changing the world"!

2023-05-15 03:47 UTC, lianginx requested changes
Thank you for your contribution, it's great! Just two translations need to be modified.

2023-05-15 03:47 UTC, lianginx commented on locales/en.json
> +          "title": "Translation: 翻译你好，快乐的世界！",
```suggestion
          "title": "Translation: 你好，快乐的世界！",
```

2023-05-15 03:47 UTC, lianginx commented on locales/en.json
> +            "content": "Translation: 翻译你好，快乐的世界！"
```suggestion
            "content": "Translation: 你好，快乐的世界！"
```

2023-05-15 09:08 UTC, itTkm commented on locales/en.json
> +          "title": "Translation: 翻译你好，快乐的世界！",
fixed: 803e0fd

2023-05-15 09:08 UTC, itTkm commented on locales/en.json
> +            "content": "Translation: 翻译你好，快乐的世界！"
fixed: 803e0fd

2023-05-15 09:27 UTC, lianginx approved these changes

2023-05-15 09:28 UTC, merged

2023-05-16 05:40 UTC, lianginx commented
I found an issue, after running `yarn build`, `node .output/server/index.mjs` will throw an error.

<img width="968" alt="image" src="https://github.com/lianginx/chatgpt-nuxt/assets/21002250/fdcf2fec-6d60-44b7-819c-95aa19c02011">